source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!
platform :ios, '8.0'

target 'FayeSwift_Example' do
  pod 'FayeSwift', :path => '../'
end

target 'FayeSwift_Tests' do
  pod 'FayeSwift', :path => '../'
end
